### PR TITLE
Add hdf5 integration to project using CMake

### PR DESCRIPTION
**Pull request by mortenskoett**
This PR will:
- Make an external hard dependency on hdf5 for the project. Now we have 2 such dependencies: **SWIG** and **hdf5** (libhdf5-dev).
- Include hdf5 library using CMake
- Include a simplifying wrapper library that has absolutely NOT been tested and might in worst case only work as inspiration to build our own. If it works. Well great.
- Update Dockerfile to install libhdf5-dev when updating packages. The pipeline has NOT been tested with this yet. **It should be.**

### CODE REVIEW

**Comment by mortenskoett** [comment]
I decided to bring it in standalone. The possibly faster index creation code will be next time! Check out the wrapper lib I included for free! Might be of help to us! ;-)

**Comment by mortenskoett** [comment]
Also I included the libs under _utilities_ as I thought that was probably the best place for the parser.

**Review by fremartini — APPROVED** [review]
💯 💯 👍

**Comment by mortenskoett** [comment]
> 💯 💯 👍

Did you by any change try any of it out? Locally/docker?

**Comment by fremartini** [comment]
> > 100 100 +1
> 
> @fremartini Did you by any change try any of it out? Locally/docker?

@mortenskoett yes i followed your readme instructions. CMake runs without problems so i assume the hdf5 parser was added successfully and can be used from main

**Comment by mortenskoett** [comment]
@fremartini cool. Yes from _main_ through _utilities_ currently.

**Review by nimertz — APPROVED** [review]
Tested locally 👍

**Pull request merged**
