### PR TITLE
Use of concrete Node instances + random sampling function + handle SWIG using CMake + restructure of project

### PR DESCRIPTION
**Pull request by mortenskoett**
**Major changes:**
- Uses concrete Node instances as internal nodes now. Query module still collects pointers to closest Nodes as pointer because it was way faster.
- Robert Floyd/Knut random sampling function is implemented for future use when implementing the insertion strategy
- The CMake pipeline now handles the construction of the SWIG python wrapper meaning that the setup is now very controllable in terms of what is linked, what flags are used etc.
- Project structure has been changed to reflect a more coherent placement of files; only the header containing the two entry points of the index are now part of the public include dir. 
- A debugging module has been added. A utilities module has been added.

### CODE REVIEW

**Comment by mortenskoett** [comment]
I know it is a kille PR. Might be more convenient to just check it out at try to run it and look at it. Also this PR contains both the concrete node instances AND the resture of the project even though I said otherwise -- Sorry about that -- it was just super much more convenient. Just write/call anything.

**Comment by mortenskoett** [comment]
I suppose problems could arise in:
1. the query-processing.cpp given the early halting code.
2. the Ann-Benchmarks test driver you wrote probably anticipates stuff, however have a look at Dockerfile.ecp to see where the python wrapper comes from now. It is essentially still the two same files, they are just generated and placed at a different location than `.../wrapper/files_generated...`.

**Review by fremartini — COMMENTED** [review]
👍

**Review by nimertz — APPROVED** [review]
Tested locally 👍

**Review by fremartini — APPROVED** [review]
👍

**Pull request merged**
